# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: POLAR - Easily manage your PDFs, web content, and notes.
description: >-
  A powerful document manager for Mac, Windows, and Linux for managing web
  content, books, and notes and supports tagging, annotation, highlighting and
  keeps track of your reading progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://getpolarized.io"
site.github.url: "https://getpolarized.io"
twitter_username: getpolarized
github_username:  burtonator

# Build settings
markdown: kramdown
theme: minima
plugins:
# - jekyll-feed

logo: https://getpolarized.io/assets/logo/icon.png

social:
  name: getpolarized
  links:
    - https://github.com/burtonator/polar-bookshelf
    - https://twitter.com/getpolarized

webmaster_verifications:
  google: j5BBM8XbyOumZOvUQGaej0asCNz6NERVdssDydibUl0

# permalink: /:categories/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ['_docs', '_blog']
exclude:
  - firebase.json
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
